site_name: Data Science Foundations
theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "indigo"
nav:
  - About: index.md
  - Introduction: introduction.md
  - Sessions:
      - Regression and Analysis: S1_Regression_and_Analysis.md
      - Inferential Statistics: S2_Inferential_Statistics.md
      - Model Selection and Validation: S3_Model_Selection_and_Validation.md
      - Feature Engineering: S4_Feature_Engineering.md
      - Unsupervised Learning: S5_Unsupervised_Learning.md
      - Bagging: S6_Bagging.md
      - Boosting: S7_Boosting.md
  - Exercises:
      - Descriptive Statistics Data Hunt: exercises/E1_Descriptive_Statistics_Data_Hunt.md
      - Inferential Statisitcs Data Hunt: exercises/E2_Inferential_Statistics_Data_Hunt.md
      - Practice with Feature Engineering: exercises/E3_Feature_Engineering.md
      - Practice with Supervised Learners: exercises/E4_Supervised_Learners.md
      - Practice with Writing Unit Tests: exercises/E5_Writing_Unit_Tests.md
  - Project: 
      - Statistical Analysis of TicTacToe: project/P1_Statistical_Analysis_of_TicTacToe.md
      - Heuristical TicTacToe Agents: project/P2_Heuristical_TicTacToe_Agents.md
      - 1-Step Look Ahead Agents: project/P3_1_Step_Look_Ahead_Agents.md
      - N-Step Look Ahead Agents: project/P4_N_Step_Look_Ahead_Agents.md
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - mdx_math
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
#   - pymdownx.superfences # causes weird hilighting
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra:
  analytics:
    provider: google
    property: "UA-114664473-1"
extra_css: [extra.css, styles.css]

# for generating styles.css for codehilite see:
# https://python-markdown.github.io/extensions/code_hilite/