site_name: Data Science Foundations
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - About: index.md
  - Introduction: introduction.md
  - Sessions:
      - Regression and Analysis: S1_Regression_and_Analysis.md
      - Inferential Statistics: S2_Inferential_Statistics.md
      - Model Selection and Validation: S3_Model_Selection_and_Validation.md
      - Feature Engineering: S4_Feature_Engineering.md
      - Unsupervised Learning: S5_Unsupervised_Learning.md
      - Bagging: S6_Bagging.md
      - Boosting: S7_Boosting.md
  - Labs:
      - Descriptive Statistics Data Hunt: labs/L1_Descriptive_Statistics_Data_Hunt.md
      - Inferential Statistics Data Hunt: labs/L2_Inferential_Statistics_Data_Hunt.md
      - Practice with Feature Engineering: labs/L3_Feature_Engineering.md
      - Practice with Supervised Learners: labs/L4_Supervised_Learners.md
      - Practice with Writing Unit Tests: labs/L5_Writing_Unit_Tests.md
  - Project: 
      - Statistical Analysis of TicTacToe: project/P1_Statistical_Analysis_of_TicTacToe.md
      - Heuristical TicTacToe Agents: project/P2_Heuristical_TicTacToe_Agents.md
      - 1-Step Look Ahead Agents: project/P3_1_Step_Look_Ahead_Agents.md
      - N-Step Look Ahead Agents: project/P4_N_Step_Look_Ahead_Agents.md
  - Extras:
      - Thinking Data: extras/X1_Thinking_Data.md
      - Probability: extras/X2_Probability.md
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - mdx_math
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
#   - pymdownx.superfences # causes weird hilighting
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra:
  generator: false
  analytics:
    provider: google
    property: "UA-114664473-1"
extra_css: [extra.css, styles.css]
copyright: Copyright &copy; 2022 Wesley Beckner

# for generating styles.css for codehilite see:
# https://python-markdown.github.io/extensions/code_hilite/
